apiVersion: v1
kind: Namespace
metadata:
  name: vlaanderen
  labels:
    name: vlaanderen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loonsimulatie
  namespace: vlaanderen
spec:
  selector:
    matchLabels:
      app: loonsimulatie
  template:
    metadata:
      labels:
        app: loonsimulatie
    spec:
      containers:
      - name: loonsimulatie
        image: xunafay/loonsimulatie:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 4000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: loonsimulatie
  namespace: vlaanderen
spec:
  selector:
    app: loonsimulatie
  ports:
  - port: 80
    targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loonsimulatie-ingress
  namespace: vlaanderen
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
spec:
  ingressClassName: haproxy
  rules:
  - host: loonsimulatie.hexodine.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loonsimulatie
            port:
              number: 80
  tls:
  - hosts:
    - loonsimulatie.hexodine.com
    secretName: loonsimulatie-cert
